# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: build
          command: |
           make
           ls
           curl -X "POST" "https://${moabi_host}/api/uploads" -H "accept:application/ld+json" -H "apikey:${moabi_api_key}" -H "Content-Type:multipart/form-data" -F "software=@./hello" -o moabi.id.json
           BINARYID=`grep "[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*" -o moabi.id.json`
           echo "UUID ${BINARYID}"
           echo "Waiting on ${BINARYID}"
           MOABISTATUS="INITIAL"
           while [ "$MOABISTATUS" != "SCANNED" ] ; do
           sleep 60
           curl -X "GET" "https://${moabi_host}/api/uploads/${BINARYID}" -H "accept:application/ld+json" -H "apikey:${moabi_api_key}" -o moabi.status.json
           MOABISTATUS="$(cat moabi.status.json| tr ',' "\n" | grep status |awk -F "\:" '{print $2}'|tr -d '"')"
           echo "CURRENT STATUS '${MOABISTATUS}'"
           done
           echo "analysis performed"
           MOABIRESULTS=`cat moabi.status.json| tr ',' "\n" | grep KPIsStatus |awk -F "\:" '{print $2}'|tr -d '"'`
           echo "RESULTS ${MOABIRESULTS}"
           if [ $MOABIRESULTS == "PASS" ] ; then
           echo "Build successful"
           else
           echo "Build failed"
           exit -1
           fi
           echo "Tests complete."

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
